<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" Version="2.21.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\3-Domain\Activator.DomainDrivenDesigner.Domain\Activator.DomainDrivenDesigner.Domain.csproj" />
    <ProjectReference Include="..\..\4-Infrastructure\Acticator.DomainDrivenDesigner.Infrastructure.AI\Activator.DomainDrivenDesigner.Infrastructure.AI.csproj" />
    <ProjectReference Include="..\..\4-Infrastructure\Activator.DomainDrivenDesigner.Infrastructure.Database.SqlServer\Activator.DomainDrivenDesigner.Infrastructure.Database.SqlServer.csproj" />
    <ProjectReference Include="..\..\5-Support\Activator.Support.Shared.Core\Activator.DomainDrivenDesigner.Support.Shared.Core.csproj" />
  </ItemGroup>

</Project>
