Create Table T_BUSINESS_ACTION
(
    ID                          UNIQUEIDENTIFIER NOT NULL,
    NAME                        NVARCHAR(255),
    CREATED_UTC                 DATETIME2 NOT NULL,
    REQUIREMENT_ID              UNIQUEIDENTIFIER,
    PARENT_BUSINESS_ACTION_ID   UNIQUEIDENTIFIER
);

ALTER TABLE dbo.T_BUSINESS_ACTION ADD CONSTRAINT PK_T_BUSINESS_ACTION_ID PRIMARY KEY (ID);
ALTER TABLE dbo.T_BUSINESS_ACTION ADD CONSTRAINT FK_T_BUSINESS_ACTION_T_REQUIREMENT FOREIGN KEY (REQUIREMENT_ID) REFERENCES T_REQUIREMENT(ID);
ALTER TABLE dbo.T_BUSINESS_ACTION ADD CONSTRAINT FK_T_BUSINESS_ACTION_T_BUSINESS_ACTION FOREIGN KEY (PARENT_BUSINESS_ACTION_ID) REFERENCES T_BUSINESS_ACTION(ID);