Create Table T_BUSINESS_MODEL
(
    ID                  UNIQUEIDENTIFIER NOT NULL,
    NAME                NVARCHAR(255),
    REQUIREMENT_ID      UNIQUEIDENTIFIER,
	RAW_DESCRIPTION		NVARCHAR(MAX),
    CONTEXT_ID          UNIQUEIDENTIFIER,
    CREATED_UTC         DATETIME2 NOT NULL
);

ALTER TABLE dbo.T_BUSINESS_MODEL ADD CONSTRAINT PK_T_BUSINESS_MODEL_ID PRIMARY KEY (ID);
ALTER TABLE dbo.T_BUSINESS_MODEL ADD CONSTRAINT FK_T_BUSINESS_MODEL_T_REQUIREMENT FOREIGN KEY (REQUIREMENT_ID) REFERENCES T_REQUIREMENT(ID);
ALTER TABLE dbo.T_BUSINESS_MODEL ADD CONSTRAINT FK_T_BUSINESS_MODEL_T_BUSINESS_CONTEXT FOREIGN KEY (CONTEXT_ID) REFERENCES T_BUSINESS_CONTEXT(ID);