Create Table T_BUSINESS_CONTEXT
(
    ID                          UNIQUEIDENTIFIER NOT NULL,
    NAME                        NVARCHAR(255),
    CREATED_UTC                 DATETIME2 NOT NULL,
    T_PROJECT_ID                UNIQUEIDENTIFIER,
);

ALTER TABLE dbo.T_BUSINESS_CONTEXT ADD CONSTRAINT PK_T_BUSINESS_CONTEXT_ID PRIMARY KEY (ID);
ALTER TABLE dbo.T_BUSINESS_CONTEXT ADD CONSTRAINT FK_T_BUSINESS_CONTEXT_T_PROJECT FOREIGN KEY (T_PROJECT_ID) REFERENCES T_PROJECT(ID);