Create Table T_BUSINESS_MODEL_PROPERTY
(
    ID                  UNIQUEIDENTIFIER NOT NULL,
    NAME                NVARCHAR(255),
    CREATED_UTC         DATETIME2 NOT NULL,
    TYPE                TINYINT NULL, 
    BUSINESS_MODEL_ID   UNIQUEIDENTIFIER,
);

ALTER TABLE dbo.T_BUSINESS_MODEL_PROPERTY ADD CONSTRAINT PK_T_BUSINESS_MODEL_PROPERTY_ID PRIMARY KEY (ID);
ALTER TABLE dbo.T_BUSINESS_MODEL_PROPERTY ADD CONSTRAINT FK_T_BUSINESS_MODEL_PROPERTY_T_BUSINESS_MODEL FOREIGN KEY (BUSINESS_MODEL_ID) REFERENCES T_BUSINESS_MODEL(ID);