Create Table dbo.T_REQUIREMENT
(
    ID  UNIQUEIDENTIFIER NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    CREATE_UTC DATETIME2 NOT NULL
    PROJECT_ID UNIQUEIDENTIFIER NULL
);

ALTER TABLE dbo.T_REQUIREMENT ADD CONSTRAINT PK_T_REQUIREMENT_ID PRIMARY KEY (ID);
ALTER TABLE dbo.T_REQUIREMENT ADD CONSTRAINT FK_T_REQUIREMENT_T_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES T_PROJECT(ID);
