Create Table dbo.T_REQUIREMENT
(
    ID  UNIQUEIDENTIFIER NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    CREATE_UTC DATETIME2 NOT NULL
);

ALTER TABLE dbo.T_REQUIREMENT ADD CONSTRAINT PK_T_REQUIREMENT_ID PRIMARY KEY (ID);
