using Common.Core.DependencyInjection;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Options;
using OllamaSharp;

namespace Activator.DomainDrivenDesigner.Infrastructure.AI.Client;

[ServiceLocate(default, ServiceType.Singleton)]
public class AIAgentClientFactory
{
    private readonly AIOptions _aiOption;

    public AIAgentClientFactory(IOptions<AIOptions> aiOptions)
    {
        _aiOption = aiOptions.Value;
    }

    public AIAgent Get(string instructions)
    {
        return Create(_aiOption, instructions, false);
    }

    public AIAgent Get(string instructions, string model, bool applyQwenToolFix = false, IList<AITool>? tools = null)
    {
        var options = new AIOptions
        {
            Endpoint = _aiOption.Endpoint,
            Model = model
        };

        return Create(options, instructions, applyQwenToolFix, tools: tools);
    }

    private AIAgent Create(AIOptions opt, string instructions, bool applyQwenToolFix, IList<AITool>? tools = null)
    {
        // --- Agent Setup ---
        var ollamaApiClient = new OllamaApiClient(
            new Uri(opt.Endpoint),
            defaultModel: opt.Model
        );
        var chatClient = applyQwenToolFix == true
                        ? new ChatClientBuilder(ollamaApiClient)                                
                                .UseFunctionInvocation(loggerFactory: null, options => { options.MaximumIterationsPerRequest = 10; })
                                .Use(client => new ToolCallingFixMiddleware(client))
                                .Build()
                        : new ChatClientBuilder(ollamaApiClient)
                                .Build();

        var chatClientAgentOptions = new ChatClientAgentOptions
        {
            ChatOptions = new ChatOptions
            {
                Temperature = 0.0f,
                Instructions = instructions,
                Tools = tools,
            }
        };

        return chatClient.AsAIAgent(
            chatClientAgentOptions
        );
    }
}

public sealed class ToolCallingFixMiddleware : DelegatingChatClient
{
    public ToolCallingFixMiddleware(IChatClient innerClient) : base(innerClient) { }

    public override async Task<ChatResponse> GetResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
    {
        // 1. Call the model
        var response = await base.GetResponseAsync(messages, options, cancellationToken);

        foreach (var message in response.Messages)
        {
            // 2. Check if the model returned plain text containing a tool invocation signature
            var textContent = TrimCodeBlockMark(message.Text);
            if (!string.IsNullOrEmpty(textContent) && textContent.Contains("\"name\"") && textContent.Contains("\"arguments\""))
            {
                try
                {
                    // Parse the raw JSON generated by Qwen
                    var jsonNode = System.Text.Json.Nodes.JsonNode.Parse(textContent);
                    var toolName = jsonNode?["name"]?.ToString();
                    var argumentsJson = jsonNode?["arguments"]?.ToJsonString();

                    if (!string.IsNullOrEmpty(toolName))
                    {
                        // 3. Convert the plain text into a valid FunctionCallContent object
                        var toolCall = new FunctionCallContent(
                            callId: Guid.NewGuid().ToString("N"),
                            name: toolName,
                            arguments: System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object?>>(argumentsJson!)
                        );

                        // 4. Wipe the plain text out and substitute it with the formal tool call structure
                        message.Contents.Clear();
                        message.Contents.Add(toolCall);
                    }
                }
                catch
                {
                    // If it's malicious or bad JSON formatting, let it fall through normally
                }
            }
        }

        return response;
    }

    private string TrimCodeBlockMark(string origin)
    {
        return origin.Replace("```json", "").Replace("```","");
    }
}