using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;

public sealed class ToolCallingFixMiddleware : DelegatingChatClient
{
    private readonly ILogger _logger;

    public ToolCallingFixMiddleware(IChatClient innerClient, ILogger logger) : base(innerClient) 
    {
        _logger = logger;
    }

    public override async Task<ChatResponse> GetResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
    {
        // 1. Call the model
        var response = await base.GetResponseAsync(messages, options, cancellationToken);

        foreach (var message in response.Messages)
        {
            // 2. Check if the model returned plain text containing a tool invocation signature
            
            if (IsToolCallRequest(message.Text, out string textContent))
            {
                try
                {
                    // Parse the raw JSON generated by Qwen
                    var jsonNode = System.Text.Json.Nodes.JsonNode.Parse(textContent);
                    var toolName = jsonNode?["name"]?.ToString();
                    var argumentsJson = jsonNode?["arguments"]?.ToJsonString();

                    if (!string.IsNullOrEmpty(toolName))
                    {
                        // 3. Convert the plain text into a valid FunctionCallContent object
                        var toolCall = new FunctionCallContent(
                            callId: Guid.NewGuid().ToString("N"),
                            name: toolName,
                            arguments: System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object?>>(argumentsJson!)
                        );

                        // 4. Wipe the plain text out and substitute it with the formal tool call structure
                        message.Contents.Clear();
                        message.Contents.Add(toolCall);
                    }
                }
                catch(Exception ex)
                {
                    _logger.LogError(ex, "Failed to parse tool call request from model response.");
                }
            }
        }

        return response;
    }

    private bool IsToolCallRequest(string origin, out string textContent)
    {
        textContent = origin.Replace("```json", "").Replace("```", "");
        return !string.IsNullOrEmpty(textContent) && textContent.Contains("\"name\"") && textContent.Contains("\"arguments\"");
    }
}