using Activator.DomainDrivenDesigner.Infrastructure.AI.Client;
using Activator.DomainDrivenDesigner.Infrastructure.AI.Model;
using Common.Core.DependencyInjection;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;

namespace Activator.DomainDrivenDesigner.Infrastructure.AI.Agents;

[ServiceLocate(default, ServiceType.Singleton)]
public class ActionGeneratorAgent
{
    private const string Instructions =
    """
    You are a expert of C# programming language. You can generate C# class files based on step-by-step instructions.
    
    Note:
    - Please follow output format.
    - Please make sure the generated C# class files are valid and can be compiled successfully.              
    """;

    private readonly AIAgent _aiAgent;

    public ActionGeneratorAgent(AIAgentClientFactory agentFactory, string model = "qwen2.5-coder:7b-instruct")
    {
        _aiAgent = agentFactory.Get(Instructions, model);
    }

    public async Task<AgentResponse<ActionGeneratorResult>> Create(string input, CancellationToken token)
    {
        return await _aiAgent
            .RunAsync<ActionGeneratorResult>(
            $"Please create following instruction to generate C# classes in C# syntax, {input}", 
            cancellationToken: token)
            .ConfigureAwait(false);
    }
}

public class QwenToolFixMiddleware : DelegatingChatClient
{
    public QwenToolFixMiddleware(IChatClient innerClient) : base(innerClient) { }

    public override async Task<ChatResponse> GetResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
    {
        // 1. Call the model
        var response = await base.GetResponseAsync(messages, options, cancellationToken);


        foreach (var message in response.Messages)
        {
            // 2. Check if the model returned plain text containing a tool invocation signature
            var textContent = message.Text;
            if (!string.IsNullOrEmpty(textContent) && textContent.Contains("\"name\"") && textContent.Contains("\"arguments\""))
            {
                try
                {
                    // Parse the raw JSON generated by Qwen
                    var jsonNode = System.Text.Json.Nodes.JsonNode.Parse(textContent);
                    var toolName = jsonNode?["name"]?.ToString();
                    var argumentsJson = jsonNode?["arguments"]?.ToJsonString();

                    if (!string.IsNullOrEmpty(toolName))
                    {
                        // 3. Convert the plain text into a valid FunctionCallContent object
                        var toolCall = new FunctionCallContent(
                            callId: Guid.NewGuid().ToString("N"),
                            name: toolName,
                            arguments: System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object?>>(argumentsJson!)
                        );

                        // 4. Wipe the plain text out and substitute it with the formal tool call structure
                        message.Contents.Clear();
                        message.Contents.Add(toolCall);
                    }
                }
                catch
                {
                    // If it's malicious or bad JSON formatting, let it fall through normally
                }
            }
        }

        return response;
    }
}