<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" Version="1.21.0" />
    <PackageReference Include="MrAdvice" Version="2.22.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.30" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\5-Support\Activator.DomainDrivenDesigner.Support.Core\Activator.DomainDrivenDesigner.Support.Core.csproj" />
    <ProjectReference Include="..\..\5-Support\Activator.Support.Shared.Core\Activator.DomainDrivenDesigner.Support.Shared.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
  </ItemGroup>
  
</Project>
